#page title
page_title                                : Timewave                                           
# Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1524345488                                
# Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://apps.apple.com/app/id1524345488                                          
# Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.

playstore_link                            :                                           
# Enter Google Play Store URL.

presskit_download_link                    : /assets/PressKit.zip #https://emilbaehr.com                                          
# Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
# Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip")



app_icon                                  : /assets/appicon.png                      
# Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.

app_name                                  : Timewave                                           
# Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.

app_price                                 : $ 1.99                                          
# Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.

app_description                           : Flowing timers for sequential tasks.

enable_smart_app_banner                   : true                                      
# Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Sahil Arayakandy                                
your_link                                 :                     
your_city                                 : bangalore, India                                
email_address                             : mdsahilak.dev@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : mdsahilak
github_username                           : mdsahilak
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Create Timers
    description                           : Create your own timers to keep track of individual tasks.
    fontawesome_icon_name                 : magic
    
  - title                                 : Chain Timers
    description                           : Chain timers together with breaks to create a Timeflow.
    fontawesome_icon_name                 : link

  - title                                 : Personalise Flow
    description                           : Add a title, subtitle and icon to make it your own
    fontawesome_icon_name                 : star

  - title                                 : Powerful Tools
    description                           : Long press on a timer to duplicate or reorder
    fontawesome_icon_name                 : sync
  
  - title                                 : Quick Play
    description                           : Tap on the Timeflow's icon to directly enter play mode
    fontawesome_icon_name                 : play-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#666666"
topbar_transparency                       : 0.3
topbar_title_color                        : "#000000"

cover_image                               : assets/background.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#EBEBEB"
cover_overlay_transparency                : 0.7

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#000000"
app_price_color                           : "#424242"
app_description_color                     : "#333333"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#434343"
feature_icons_background_color            : "#EFEFEF"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
  - vendor

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
